# Generated by Django 4.1.3 on 2022-11-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_myuser_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpurchase',
            options={'ordering': ['date']},
        ),
    ]
