# Generated by Django 4.1.3 on 2022-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_returnpurchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpurchase',
            options={'ordering': ['-date']},
        ),
    ]
