# Generated by Django 4.1.3 on 2022-11-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_returnpurchase_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.purchase'),
        ),
    ]
