# Generated by Django 4.1.3 on 2022-11-23 09:43

from django.db import migrations


def add_product(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Product.objects.create(title='Voltage regulator',
                           description='1000VA min.150v max.270V',
                           price='60',
                           quantity='5')
    Product.objects.create(title='UPS',
                           description='online 1500VA battery 28Ah',
                           price='630',
                           quantity='6')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_returnpurchase_purchase'),
    ]

    operations = [
        migrations.RunPython(add_product, lambda x, y: None),
    ]
